# Generated by Django 6.0 on 2025-12-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Transfer Bank'), ('ewallet', 'E-Wallet'), ('cod', 'COD (Cash on Delivery)'), ('credit_card', 'Kartu Kredit')], default='bank_transfer', max_length=20),
        ),
    ]
