# Generated by Django 6.0 on 2025-12-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
